name: plactice create-pull-request

on: 
  push:
    branches-ignore:
      - 'master'
      - 'bot/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Update time
      run: |
        node index.js

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - uses: peter-evans/create-pull-request@v2.7.0
      name: Create Pull Request
      id: cpr
      with:
        token: ${{ secrets.BOT_TOKEN }}
        base: master
        branch: "bot/${{ steps.extract_branch.outputs.branch }}"
        branch-suffix: short-commit-hash
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
